### ISSUE TITLE
Build jar still comes out as addressbook.jar

### ISSUE THREAD

**Issue by Q-gabe** [AY1920S1-CS2103T-F12-2/main#101]
To whoever has time to fix! 🙏 
Not sure if changing it through build.gradle would cause anything to break.

**Comment by gachia** [comment]
![image](https://user-images.githubusercontent.com/8081866/67914356-d6f72f00-fbca-11e9-83ef-620e79f2c7e5.png)
Is this what you are asking? I managed to change it, however the logs still come out as AddressBook though (since we didn't change it).

**Comment by Q-gabe** [comment]
<img width="327" alt="Screenshot 2019-10-31 at 10 42 18 AM" src="https://user-images.githubusercontent.com/41467676/67914447-1e7dbb00-fbcb-11e9-8741-64121f4bf902.png">
^ The build file hahaha but yea the logs are still AB3. You fixed the build file naming?

**Comment by gachia** [comment]
![image](https://user-images.githubusercontent.com/8081866/67914536-6866a100-fbcb-11e9-87fb-f689d89592dd.png)

yea, you need to access the shadowJar parameters in build.gradle and change the name.

**Comment by Q-gabe** [comment]
Okay sweet can go ahead and include this in your next PR bah. Thanks dude 👍 👍
