### ISSUE TITLE
Appointments generates with a non-semantic example

### ISSUE THREAD

**Issue by Q-gabe** [AY1920S1-CS2103T-F12-2/main#98]
<img width="503" alt="Screenshot 2019-10-31 at 3 04 52 AM" src="https://user-images.githubusercontent.com/41467676/67890195-36354f00-fb8b-11e9-9087-5aa7cc53b05e.png">

Think it might be better if Appointments would generate with something that actual event data, even if this is a placeholder for it. But for v1.3 I think other teams will be looking at it haha. :sweat: Really low priority though, just my 2c.

**Comment by ReignOfComputer** [comment]
TBD 2359

**Comment by Q-gabe** [comment]
This was resolved. Not sure if you did or @gachia did it haha. Thanks guys.
